### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call

### ISSUE THREAD

**Issue by crazyrobbin** [ParkSangGwon/TedImagePicker#11]
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalStateException: getString(getColumnIndex(dateTaken)) must not be null
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: getString(getColumnIndex(dateTaken)) must not be null
        at gun0912.tedimagepicker.util.GalleryUtil$Companion.getImage(GalleryUtil.kt:91)
        at gun0912.tedimagepicker.util.GalleryUtil$Companion.access$getImage(GalleryUtil.kt:15)
        at gun0912.tedimagepicker.util.GalleryUtil$Companion$getMedia$1$albumList$1$totalImageList$2.invoke(GalleryUtil.kt:44)
        at gun0912.tedimagepicker.util.GalleryUtil$Companion$getMedia$1$albumList$1$totalImageList$2.invoke(GalleryUtil.kt:15)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:702)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:732)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:723)
        at gun0912.tedimagepicker.util.GalleryUtil$Companion$getMedia$1.subscribe(GalleryUtil.kt:45)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by ParkSangGwon** [comment]
@crazyrobbin 
fixed v1.0.2
