### ISSUE TITLE
White screen below API level 29

### ISSUE THREAD

**Issue by LebonNic** [ParkSangGwon/TedImagePicker#118]
Hello,

Since the 1.4.0 update, I can no longer open the image picker. I have a blank screen and no media appears. It starts from API level 28 and below. Above 28 everything works (29+ ✔️). In the logs I have the following error:

```
2023-01-09 17:20:01.266 29842-29842 DadaApplication    com...talplumecompany.dada  E  Uncaught Exception detected in thread {Thread[main,5,main]}: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.database.sqlite.SQLiteException: no such column: duration (code 1): , while compiling: SELECT _id, _data, bucket_display_name, date_added, duration FROM images ORDER BY date_added DESC
                                                                                                    #################################################################
                                                                                                    Error Code : 1 (SQLITE_ERROR)
                                                                                                    Caused By : SQL(query) error or missing database.
                                                                                                    	(no such column: duration (code 1): , while compiling: SELECT _id, _data, bucket_display_name, date_added, duration FROM images ORDER BY date_added DESC)
                                                                                                    #################################################################
2023-01-09 17:20:01.268 29842-29842 DadaApplication    com...talplumecompany.dada  E  io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.database.sqlite.SQLiteException: no such column: duration (code 1): , while compiling: SELECT _id, _data, bucket_display_name, date_added, duration FROM images ORDER BY date_added DESC
                                                                                                    #################################################################
                                                                                                    Error Code : 1 (SQLITE_ERROR)
                                                                                                    Caused By : SQL(query) error or missing database.
                                                                                                    	(no such column: duration (code 1): , while compiling: SELECT _id, _data, bucket_display_name, date_added, duration FROM images ORDER BY date_added DESC)
                                                                                                    #################################################################
                                                                                                    	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                                                    	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                                                    	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
                                                                                                    	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
                                                                                                    	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:789)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6944)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                                                                    Caused by: android.database.sqlite.SQLiteException: no such column: duration (code 1): , while compiling: SELECT _id, _data, bucket_display_name, date_added, duration FROM images ORDER BY date_added DESC
                                                                                                    #################################################################
                                                                                                    Error Code : 1 (SQLITE_ERROR)
                                                                                                    Caused By : SQL(query) error or missing database.
                                                                                                    	(no such column: duration (code 1): , while compiling: SELECT _id, _data, bucket_display_name, date_added, duration FROM images ORDER BY date_added DESC)
                                                                                                    #################################################################
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
                                                                                                    	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                                                    	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:760)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:710)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:668)
                                                                                                    	at gun0912.tedimagepicker.util.GalleryUtil$Companion.getAllMediaList(GalleryUtil.kt:84)
                                                                                                    	at gun0912.tedimagepicker.util.GalleryUtil$Companion.getMedia$lambda-6(GalleryUtil.kt:30)
                                                                                                    	at gun0912.tedimagepicker.util.GalleryUtil$Companion.$r8$lambda$MEh2T-ij7_phM_p2hSXHbj5lEI4(Unknown Source:0)
                                                                                                    	at gun0912.tedimagepicker.util.GalleryUtil$Companion$$ExternalSyntheticLambda0.subscribe(Unknown Source:4)
                                                                                                    	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                                    	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)

```

I have the feeling that the problem was introduced after this commit: https://github.com/ParkSangGwon/TedImagePicker/commit/306703911869745ed68e6ed9cb4d66e46bc98b66#diff-0ecf79ec70b0d7f182b802768b916498d772aebdb6f61dc7da7efba952b93370

**Comment by mericgerceker** [comment]
Hello, i have the same error

**Comment by ted-prnd** [comment]
Thanks guys.
This issue solved at https://github.com/ParkSangGwon/TedImagePicker/pull/119
You can use 1.4.1 after few minute
