### ISSUE TITLE
library doesn't display images when working on Android 10

### ISSUE THREAD

**Issue by assanee** [ParkSangGwon/TedImagePicker#24]
2019-12-24 19:07:09.217 5871-9629/? E/Parcel: Class not found when unmarshalling: gun0912.tedimagepicker.builder.TedImagePicker$Builder
    java.lang.ClassNotFoundException: gun0912.tedimagepicker.builder.TedImagePicker$Builder
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8548)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:755)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:666)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1749)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:597)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1604)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1501)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1455)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1658)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
     Caused by: java.lang.ClassNotFoundException: gun0912.tedimagepicker.builder.TedImagePicker$Builder
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031) 
        at android.os.Parcel.readParcelable(Parcel.java:2981) 
        at android.os.Parcel.readValue(Parcel.java:2883) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getString(BaseBundle.java:1160) 
        at android.content.Intent.getStringExtra(Intent.java:8548) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:755) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:666) 
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1749) 
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:597) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1604) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1501) 
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1455) 
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1658) 
        at android.os.Binder.execTransactInternal(Binder.java:1021) 
        at android.os.Binder.execTransact(Binder.java:994)

**Comment by assanee** [comment]
I found a solution : 
https://stackoverflow.com/a/58289588/6863232
