### ISSUE TITLE
Ted Image Picker Activity Crashes due to date parsing issue

### ISSUE THREAD

**Issue by adeel-quantumcph** [ParkSangGwon/TedImagePicker#27]
i am getting following error, currently this error occured on the Android OS Version 19 & 22

`java.lang.IllegalArgumentException: Unknown pattern character 'Y'
	 at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:314)
	 at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:296)
	 at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:356)
	 at gun0912.tedimagepicker.TedImagePickerActivity$setupMediaRecyclerView$$inlined$run$lambda$1.onScrolled(TedImagePickerActivity.kt:211)
	 at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
	 at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5338)
	 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
	 at android.view.Choreographer.doCallbacks(Choreographer.java:586)
	 at android.view.Choreographer.doFrame(Choreographer.java:555)
	 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
	 at android.os.Handler.handleCallback(Handler.java:739)
	 at android.os.Handler.dispatchMessage(Handler.java:95)
	 at android.os.Looper.loop(Looper.java:160)
	 at android.app.ActivityThread.main(ActivityThread.java:5541)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at java.lang.reflect.Method.invoke(Method.java:372)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)`

**Comment by kateile** [comment]
this is similar to #9

**Comment by ParkSangGwon** [comment]
@adeel-quantumcph @kateile 
What is your library version
This issue resolved at e7ab8070b7bed2b9e3f31e21460024b186c8804f

**Comment by adeeljavedch** [comment]
@ParkSangGwon  yes it was fixed in latest version. Latest version was not updated on ReadMe and so i added the old library but later updated to the latest one.
