### ISSUE TITLE
이렇게 나오는건 왜일까요?

### ISSUE THREAD

**Issue by fredchoi** [ParkSangGwon/TedImagePicker#4]
07-01 15:06:17.906 422-422/com.buildonenetworks.cutalk0001 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.buildonenetworks.cutalk0001, PID: 422
    a.a.c.f: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at a.a.j.a.onError(RxJavaPlugins.java:367)
        at a.a.f.d.k.onSuccess(ConsumerSingleObserver.java:65)
        at a.a.f.e.g.d$a.onSuccess(SingleCreate.java:67)
        at com.b.b.a.a$a$1$1.onPermissionGranted(TedRx2Permission.java:32)
        at com.gun0912.tedpermission.TedPermissionActivity.a(TedPermissionActivity.java:200)
        at com.gun0912.tedpermission.TedPermissionActivity.a(TedPermissionActivity.java:177)
        at com.gun0912.tedpermission.TedPermissionActivity.onCreate(TedPermissionActivity.java:80)
        at android.app.Activity.performCreate(Activity.java:6877)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
        at android.app.ActivityThread.access$1100(ActivityThread.java:222)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7230)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:740)
        at android.app.ContextImpl.startActivity(ContextImpl.java:727)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
        at com.gun0912.tedonactivityresult.ProxyActivity.startActivityForResult(ProxyActivity.java:31)
        at com.b.a.a.a$a.startActivityForResult(TedRxOnActivityResult.java:36)
        at gun0912.tedimagepicker.builder.TedImagePickerBaseBuilder.c(TedImagePickerBaseBuilder.kt:86)
        at gun0912.tedimagepicker.builder.TedImagePickerBaseBuilder.access$startActivity(TedImagePickerBaseBuilder.kt:28)
        at gun0912.tedimagepicker.builder.TedImagePickerBaseBuilder$d.accept(TedImagePickerBaseBuilder.kt:72)
        at gun0912.tedimagepicker.builder.TedImagePickerBaseBuilder$d.accept(TedImagePickerBaseBuilder.kt:28)
        at a.a.f.d.k.onSuccess(ConsumerSingleObserver.java:62)
        at a.a.f.e.g.d$a.onSuccess(SingleCreate.java:67) 
        at com.b.b.a.a$a$1$1.onPermissionGranted(TedRx2Permission.java:32) 
        at com.gun0912.tedpermission.TedPermissionActivity.a(TedPermissionActivity.java:200) 
        at com.gun0912.tedpermission.TedPermissionActivity.a(TedPermissionActivity.java:177) 
        at com.gun0912.tedpermission.TedPermissionActivity.onCreate(TedPermissionActivity.java:80) 
        at android.app.Activity.performCreate(Activity.java:6877) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7230) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ParkSangGwon** [comment]
@fredchoi 이 코드를 어디서 실행하셨나요
```
 Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
```
이 문제가 주요 이유 입니다.
