### ISSUE TITLE
Caused by java.lang.IllegalStateException getString(getColumnIndex(dateTaken)) must not be null

### ISSUE THREAD

**Issue by demo-Ashif** [ParkSangGwon/TedImagePicker#9]
Getting this issue and my app is crashing specially in xiaomi and samsung devices. giving full error log. 
`Caused by java.lang.IllegalStateException: getString(getColumnIndex(dateTaken)) must not be null
       at gun0912.tedimagepicker.util.GalleryUtil$Companion.access$getAlbum(GalleryUtil.java:55)
       at gun0912.tedimagepicker.util.GalleryUtil$Companion.access$getAlbum(GalleryUtil.java)
       at gun0912.tedimagepicker.util.GalleryUtil$Companion$getMedia$1$albumList$1$totalImageList$2.invoke(GalleryUtil.java:7)
       at gun0912.tedimagepicker.util.GalleryUtil$Companion$getMedia$1$albumList$1$totalImageList$2.invoke(GalleryUtil.java:2)
       at kotlin.sequences.TransformingSequence$iterator$1.next + 12(TransformingSequence.java:12)
       at kotlin.sequences.SequencesKt___SequencesKt.map(SequencesKt___SequencesKt.java:20)
       at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(SequencesKt___SequencesKt.java:10)
       at kotlin.sequences.SequencesKt___SequencesKt.toList(SequencesKt___SequencesKt.java:5)
       at kotlin.sequences.SequencesKt.toList(SequencesKt.java)
       at gun0912.tedimagepicker.util.GalleryUtil$Companion$getMedia$1.subscribe(GalleryUtil.java:123)
       at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:10)
       at io.reactivex.Single.create(Single.java:14)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run + 2(SingleSubscribeOn.java:2)
       at io.reactivex.Scheduler$DisposeTask.run + 9(Scheduler.java:9)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run + 13(ScheduledRunnable.java:13)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java)
       at java.util.concurrent.FutureTask.run + 266(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run + 301(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 764(Thread.java:764)`

**Comment by jamacco94** [comment]
+ the same issue

**Comment by ivaninho19** [comment]
me too

**Comment by ParkSangGwon** [comment]
@demo-Ashif @jamacco94 @ivaninho19  
fixed v1.0.2
