### ISSUE TITLE
crashing on clicking camera tile

### ISSUE THREAD

**Issue by kaushalxb** [ParkSangGwon/TedImagePicker#93]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tansh.seller, PID: 15643
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:448)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
        at java.io.File.createTempFile(File.java:2001)
        at gun0912.tedimagepicker.util.MediaUtil$Companion.getMediaUri(MediaUtil.kt:74)
        at gun0912.tedimagepicker.util.MediaUtil$Companion.getMediaIntentUri$tedimagepicker_release(MediaUtil.kt:36)
        at gun0912.tedimagepicker.TedImagePickerActivity.onCameraTileClick(TedImagePickerActivity.kt:272)
        at gun0912.tedimagepicker.TedImagePickerActivity.access$onCameraTileClick(TedImagePickerActivity.kt:51)
        at gun0912.tedimagepicker.TedImagePickerActivity$setupMediaRecyclerView$1$1.onHeaderClick(TedImagePickerActivity.kt:211)
        at gun0912.tedimagepicker.base.BaseRecyclerViewAdapter.onCreateViewHolder$lambda-3$lambda-2$lambda-1(BaseRecyclerViewAdapter.kt:65)
        at gun0912.tedimagepicker.base.BaseRecyclerViewAdapter.$r8$lambda$G4f8iCvpCvLkBKPTvAk0G9hLuVA(Unknown Source:0)
        at gun0912.tedimagepicker.base.BaseRecyclerViewAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by dreamboy1339** [comment]
Hi, there. 

I had this same issue. but I fixed it. 

my solution is requesting and granting WRITE_EXTERNAL_STORAGE permission. 

In your app, request WRITE_EXTERNAL_STORAGE permission. 

MediaUtil class that make media uri use `File.createTempFile` method that write somewhere in storage.

So if your app has not WRITE_EXTERNAL_STORAGE permission, the app is crashed because of write permission.

error occurred in android 6 to 9.

I wish you all the best.

**Comment by ParkSangGwon** [comment]
https://github.com/ParkSangGwon/TedImagePicker/pull/91 can be solution
